FROM node:lts-alpine3.12
LABEL maintainer="fiskolini@gmail.com"

WORKDIR "/app"

# Disable interaction
ARG DEBIAN_FRONTEND=noninteractive

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
#COPY package*.json ./

#RUN npm install

# Bundle app source
# COPY . .

# CMD [ "node_modules/.bin/open-swagger-ui", "./openapi.json", "--open" ]
